Us06displayOfferTable
WildCodeSchool-2024-02/JS-lyon-0224-P3-careercatchers pull request #17
Opened 2024-06-05 14:41 UTC by wilderLPM

Configuration de la méthode readAll() pour la table 'offer' => lien back/front fonctionnel pour la controller function browse()

2024-06-05 14:55 UTC, bastien-fournier commented on server/app/config.js
Comment line 53

2024-06-05 14:55 UTC, bastien-fournier commented on server/app/config.js
> +app.use(express.json());
Comment line 53

2024-06-05 15:07 UTC, bastien-fournier approved these changes
All good

2024-06-06 07:53 UTC, HazeFury commented on server/database/schema.sql
> +  job_type VARCHAR(255) NOT NULL
pour le job type, je ne pense pas qu'un varchar de 255 caractères soit nécessaire (Je vois qu'a priori, ce serait pour caler des trucs genre "CDI", "CDD" toussa) donc 255 me parait un peu trop ^^

pour le job title => se poser aussi la question de combien vous pourriez avoir besoin ==> peut -être que 150 peut suffire ? à vous de voir 😉 

L'idée que je vous dire, c'est de pas mettre des 255 par défaut. Il faut toujours réfléchir à ce qu'on à besoin de stocker dans un champs pour savoir quelle longueur définir 👍

2024-06-06 07:54 UTC, HazeFury requested changes
Beau boulot 👍 

Juste une modif à faire pour la longueur des VARCHAR ^^

2024-06-06 08:22 UTC, merged