PR de dev sur main Sprint 1
WildCodeSchool-2024-02/JS-lyon-0224-P3-careercatchers pull request #27
Opened 2024-06-07 08:21 UTC by AnnesophieMarchet

12 Users Stories engagé
PR sprint 1, 40 points PP

US 01 [Technique] Mise en place des dossiers  PP 2/10
US 02 [Technique] Créer les routes  PP 2/10
US 03 [Backend] Création de la table offer  PP 4/10
US 04 [Backend] Remplissage de la table offer PP 6/10
US 05 [Backend] Créer la table table_Company PP 3/10
US 06 [Back + Front - HomePage] Afficher les données de la table offer 8/10
US 07 [Front] Création du composant Logo PP 2/10
+rajout:
US 13[Backend] Remplir la Table Company
US 14 [Front - ResultPage] Créer la page ResultPage
US 15 [Back + Front - HomePage] Relier la table company du back au front PP 5/10
US 16 [Front] Variables PP 2/10
US 09 [Front] Création HomeButtons PP 2/10

2024-06-07 08:43 UTC, HazeFury approved these changes
Beau boulot, bravo 👍 💯

2024-06-13 14:41 UTC, wilderLPM commented
SPRINT 2 TERMINÉ
12 US engagées pour 56 PP
2 US rajoutées
9 réalisées : 

US 08 [Front] Création du composant ExternaticDescription PP 2/10
US 10 [Front - ResultPage] Création du composant BurgerMenu PP 6/10
US 11 [Front] Création du composant NavBar Mobile PP 4/10
US 17 [Front] SignUpButton in Homepage Component PP 3/10
US 18 [Front] CSS HomePage.jsx PP 4/10
US23 [Back] Créer la clef étrangère company_id dans la table offer  PP 3/10
US24 [Back+Front] Sur ResultPage.jsx afficher les offres d' emploi et l' entreprise qui à fait l' offre PP 8/10
US25 [Technique] configuration de tailwind sur le projet PP 5/10
US26 [Front- NavBarMobile] Animer et peaufiner les éléments de la barre de navigation PP 3/10

2024-06-13 15:09 UTC, wildmatthieu requested changes

2024-06-13 15:09 UTC, wildmatthieu commented on server/app/routers/api/companies/router.js
>  // Route to get a list of items
commentaire à adapter : "list of compagnies"

2024-06-13 15:29 UTC, merged