Us21 sign up page css
WildCodeSchool-2024-02/JS-lyon-0224-P3-careercatchers pull request #44
Opened 2024-06-16 12:06 UTC by AnnesophieMarchet

2024-06-16 12:14 UTC, bastien-fournier requested changes

2024-06-16 12:14 UTC, bastien-fournier commented on client/src/components/Form/Form.jsx
> +      <form onSubmit={handleSubmit} className="">
class name empty

2024-06-16 20:00 UTC, AnnesophieMarchet commented on client/src/components/Form/Form.jsx
> +      <form onSubmit={handleSubmit} className="">
className fix

2024-06-16 20:03 UTC, wilderLPM approved these changes
Great job

2024-06-17 09:30 UTC, StoicFrenchDev requested changes

2024-06-17 09:30 UTC, StoicFrenchDev commented on client/src/pages/SignUpPage.jsx
> +      <div style={{ width: "120px", height: "90px" }} className="flex mx-auto">
Style should be moved to the CSS file.

2024-06-17 14:58 UTC, StoicFrenchDev approved these changes

2024-06-17 15:05 UTC, bastien-fournier approved these changes
All good

2024-06-17 15:08 UTC, merged