put data from user into table candidate firstname, lastname, birthday
WildCodeSchool-2024-02/JS-lyon-0224-P3-careercatchers pull request #51
Opened 2024-06-18 14:56 UTC by bastien-fournier

2024-06-18 15:05 UTC, wildmatthieu commented
Dans cette US du front et du back (BDD) sont faits : 
- il me faut dans l'US (sur trello par exemple) le screen de la maquette sur la partie concernée 
- il me faut le screen du MPD à jour par rapport à cette US

Que veut dire [back] aussi dans l'US ? (dans la liste des points)

2024-06-18 15:05 UTC, wilderLPM approved these changes
All good !

2024-06-18 15:35 UTC, HazeFury commented on client/src/main.jsx
J'imagine que le code marche bien et il est propre mais je trouve que c'est pas ouf de mettre tout ce gros bloc de code dans le main.jsx . 
Il est de bonne usage de garder un main assez propre et pas trop chargé (typiquement vous avez une quarantaine de lignes de code pour une fonction de post. Comment va évoluer le main si vous avez une dizaine de fonctions similaires ? (ce qui peut facilement arriver))

Vous avez donc 2 options intéressantes : 
- Soit vous gardez votre action sur la route mais vous définissez votre fonction dans un fichier a part puis vous l'importer dans main puis l'appeler dans votre action
- Soit vous passez par une fonction dans le composant de signup directement (et vous retirez l'action dans le main)

2024-06-18 15:37 UTC, HazeFury requested changes
un commentaire à prendre en compte

2024-06-19 12:12 UTC, bastien-fournier commented on client/src/main.jsx
Hello marco, pour régler cette us on voulait faire un nouvelle US est ce que tu penses que tu peux valider celle ci et on va la reprendre j'ai créer la nouvelle us voici le lien : https://trello.com/c/zGLB8M2z/69-us-41-technique-cr%C3%A9ation-de-fonction-pour-r%C3%A9cup%C3%A9rer-donn%C3%A9e-du-front-vers-la-bdd

2024-06-19 13:45 UTC, bastien-fournier commented on client/src/main.jsx
Peux tu valider la PR stp, nous avons créer une us 40 https://trello.com/c/cAy1mTri/68-us40frontv%C3%A9rifier-que-les-deux-mots-de-passe-son-les-m%C3%AAmes-pour-la-connexion-de-lutilisateur qui est faite et que nous push quand cette pr sera validé merci

2024-06-19 14:41 UTC, HazeFury approved these changes
ok

2024-06-19 14:44 UTC, merged